/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar categorias activas
         * @description Devuelve las categorias activas ordenadas por su campo de orden. Sin paginacion: son pocas y se usan para armar el menu.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Listado de categorias */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos: components["schemas"]["Categoria"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar productos
         * @description Listado paginado y liviano, pensado para la grilla del catalogo. Incluye el precio minimo entre las variantes activas, si hay stock, y solo la imagen principal.
         *
         *     Para los datos completos de un producto, usar el detalle por slug.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Numero de pagina, empezando en 1. */
                    pagina?: components["parameters"]["Pagina"];
                    /** @description Cantidad de elementos por pagina. */
                    limite?: components["parameters"]["Limite"];
                    /** @description Slug de la categoria. Ej: jabones. */
                    categoria?: string;
                    /** @description Si es true, devuelve solo los productos marcados como destacados. */
                    destacados?: boolean;
                    /** @description Texto de busqueda. Busca en nombre y descripcion corta. */
                    q?: string;
                    /** @description Criterio de ordenamiento. `defecto`: orden de categoria y despues alfabetico. `precio_asc` / `precio_desc`: por precio minimo de variante activa. `mas_vendidos`: declarado en el contrato pero no implementado todavia; hasta que existan ventas reales devuelve el orden por defecto. */
                    orden?: "defecto" | "precio_asc" | "precio_desc" | "mas_vendidos";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Listado paginado de productos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos: components["schemas"]["ProductoListado"][];
                            meta: components["schemas"]["Meta"];
                        };
                    };
                };
                /** @description Parametros invalidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "DATOS_INVALIDOS",
                         *       "details": {
                         *         "limite": "Debe ser un número entre 1 y 50"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de un producto
         * @description Ficha completa: todas las variantes activas, todas las imagenes, ingredientes y modo de uso.
         *
         *     Se busca por slug y no por id porque el slug es lo que va en la URL publica y en los links que se comparten.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Slug del producto. Ej: jabon-calendula-karite. */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Producto encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductoDetalle"];
                    };
                };
                /** @description No existe un producto activo con ese slug */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "NO_ENCONTRADO"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesion en el panel
         * @description Verifica las credenciales y deja la sesion en una cookie httpOnly llamada velua_sesion. El token nunca viaja en el cuerpo de la respuesta. Limitado a 10 intentos cada 15 minutos por IP.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginEntrada"];
                };
            };
            responses: {
                /** @description Sesion iniciada. La cookie viene en el encabezado Set-Cookie. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                /** @description Datos invalidos */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Mail o contraseña incorrectos. No se distingue cual de los dos. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "CREDENCIALES_INVALIDAS"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Usuario desactivado */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "USUARIO_INACTIVO"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Demasiados intentos */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "LIMITE_SUPERADO"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesion
         * @description Borra la cookie de sesion. Responde 204 aunque no hubiera sesion.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sesion cerrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuario de la sesion actual
         * @description Devuelve el usuario logueado con sus permisos. El frontend lo usa para saber si hay sesion y que mostrar. Verifica que el usuario siga activo, aunque el token todavia no haya expirado.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usuario de la sesion */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                /** @description Sin sesion, token invalido o expirado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "TOKEN_EXPIRADO"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar productos para la grilla del panel
         * @description Incluye los inactivos. Cada fila trae cuantas variantes activas tiene, el precio minimo, el stock total y cuantas imagenes cargadas, para poder ver de un vistazo que falta completar.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Numero de pagina, empezando en 1. */
                    pagina?: components["parameters"]["Pagina"];
                    /** @description Cantidad de elementos por pagina. */
                    limite?: components["parameters"]["Limite"];
                    /** @description Busca en nombre y slug. */
                    q?: string;
                    categoriaId?: number;
                    estado?: "todos" | "activos" | "inactivos";
                    /** @description `recientes` es el orden por defecto. `stock` ordena de menor a mayor stock total, que es lo util para ver que hay que reponer. */
                    orden?: "recientes" | "nombre" | "stock";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Productos paginados */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos: components["schemas"]["ProductoAdminFila"][];
                            meta: components["schemas"]["Meta"];
                        };
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
            };
        };
        put?: never;
        /**
         * Crear un producto con sus variantes
         * @description El producto y sus variantes se crean juntos en una transaccion: el esquema exige al menos una variante, asi que un producto sin ellas quedaria invalido.
         *
         *     Reglas de importes: se aceptan con punto o coma y se guardan con dos decimales. `precioAnterior` tiene que ser MAYOR que `precio`; si fuera igual o menor, la tienda mostraria un descuento de cero por ciento.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductoEntrada"];
                };
            };
            responses: {
                /** @description Producto creado, con su ficha completa */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductoAdmin"];
                    };
                };
                /** @description Datos invalidos, o SIN_VARIANTES si no se cargo ninguna. En DATOS_INVALIDOS, details indica el campo con la posicion dentro de la lista, por ejemplo "variantes[1].precio". */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "DATOS_INVALIDOS",
                         *       "details": {
                         *         "variantes[1].precioAnterior": "Tiene que ser mayor que el precio actual"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/productos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ficha completa de un producto
         * @description Incluye TODAS las variantes, activas e inactivas, con su stock real, y todas las imagenes con su id, que el panel necesita para borrarlas.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Producto */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductoAdmin"];
                    };
                };
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar un producto
         * @description Solo se modifican los campos que vienen. NO toca las variantes: cada una tiene sus propios endpoints. Cambiar el nombre no cambia el slug.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductoCambios"];
                };
            };
            responses: {
                /** @description Producto actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductoAdmin"];
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
            };
        };
        trace?: never;
    };
    "/admin/productos/{id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Publicar o despublicar un producto */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        activo: boolean;
                    };
                };
            };
            responses: {
                /** @description Producto con su estado nuevo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductoAdmin"];
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        trace?: never;
    };
    "/admin/productos/{id}/variantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agregar una variante */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VarianteEntrada"];
                };
            };
            responses: {
                /** @description Producto con la variante agregada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductoAdmin"];
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
                /** @description El SKU ya lo usa otra variante */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "CONFLICTO_DE_DATOS"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/productos/{id}/variantes/{varianteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar una variante
         * @description Si se cambia `precioAnterior` sin cambiar `precio`, se valida contra el precio que ya tiene la variante. Enviar `precioAnterior` en null quita la oferta.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                    /** @description Id de la variante dentro del producto. */
                    varianteId: components["parameters"]["VarianteIdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VarianteCambios"];
                };
            };
            responses: {
                /** @description Producto con la variante actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductoAdmin"];
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                /** @description No existe el producto, o la variante no es de ese producto */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "NO_ENCONTRADO"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                409: components["responses"]["Conflicto"];
            };
        };
        trace?: never;
    };
    "/admin/productos/{id}/variantes/{varianteId}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Activar o desactivar una variante
         * @description Las variantes no se borran nunca: los pedidos historicos las referencian. Desactivada desaparece de la tienda sin perder el vinculo.
         *
         *     No se puede desactivar la ultima variante activa: quedaria un producto visible que no se puede comprar. En ese caso responde ULTIMA_VARIANTE_ACTIVA.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                    /** @description Id de la variante dentro del producto. */
                    varianteId: components["parameters"]["VarianteIdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        activa: boolean;
                    };
                };
            };
            responses: {
                /** @description Producto con la variante actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductoAdmin"];
                    };
                };
                /** @description Datos invalidos, o ULTIMA_VARIANTE_ACTIVA */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "ULTIMA_VARIANTE_ACTIVA"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        trace?: never;
    };
    "/admin/productos/{id}/imagenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar las imagenes de un producto */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Imagenes ordenadas. La primera es la principal. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos: components["schemas"]["ImagenAdmin"][];
                        };
                    };
                };
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        /**
         * Subir una imagen
         * @description Se envia como multipart/form-data, con el archivo en el campo `imagen` y opcionalmente un texto alternativo en `alt`.
         *
         *     Formatos aceptados: jpg, png y webp. Tope de 5 MB. El contenido se verifica mirando los primeros bytes del archivo, no el tipo que declara el navegador, que se puede falsear.
         *
         *     La imagen se guarda en el proveedor achicada a 1600 px de lado mayor. Los tamanos para cada pantalla salen transformando la URL, sin subir nada adicional. Maximo 8 imagenes por producto.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        imagen: string;
                        /** @description Texto alternativo para accesibilidad. */
                        alt?: string;
                    };
                };
            };
            responses: {
                /** @description Galeria actualizada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos?: components["schemas"]["ImagenAdmin"][];
                        };
                    };
                };
                /** @description ARCHIVO_REQUERIDO, TIPO_ARCHIVO_INVALIDO, ARCHIVO_DEMASIADO_GRANDE o LIMITE_IMAGENES. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "ARCHIVO_DEMASIADO_GRANDE"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
                /** @description El proveedor de imagenes rechazo la subida. */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "ERROR_AL_SUBIR"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/productos/{id}/imagenes/orden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reordenar la galeria
         * @description La primera imagen es la principal: es la que se ve en la grilla de la tienda. Recibe los ids de TODAS las imagenes del producto en el orden deseado; un orden parcial dejaria dos en la misma posicion y la principal seria impredecible.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @example [
                         *       5,
                         *       3,
                         *       4
                         *     ]
                         */
                        ids: number[];
                    };
                };
            };
            responses: {
                /** @description Galeria en el orden nuevo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos?: components["schemas"]["ImagenAdmin"][];
                        };
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/productos/{id}/imagenes/{imagenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Borrar una imagen
         * @description Borra el archivo del proveedor y despues la fila. Si el borrado remoto falla, la fila se borra igual: un archivo huerfano molesta menos que una fila apuntando a una imagen que ya no existe, que dejaria la tienda con una foto rota.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                    /** @description Id de la imagen dentro del producto. */
                    imagenId: components["parameters"]["ImagenIdRuta"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Galeria sin la imagen borrada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos?: components["schemas"]["ImagenAdmin"][];
                        };
                    };
                };
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                /** @description No existe el producto, o la imagen no es de ese producto */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "NO_ENCONTRADO"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Cambiar el texto alternativo */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                    /** @description Id de la imagen dentro del producto. */
                    imagenId: components["parameters"]["ImagenIdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        alt?: string | null;
                    };
                };
            };
            responses: {
                /** @description Galeria actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos?: components["schemas"]["ImagenAdmin"][];
                        };
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        trace?: never;
    };
    "/admin/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas las categorias
         * @description Incluye las inactivas. Cada una trae cuantos productos activos tiene, para poder avisar antes de desactivarla: desactivar una categoria oculta todos sus productos de la tienda.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categorias ordenadas por su campo orden */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos: components["schemas"]["CategoriaAdmin"][];
                        };
                    };
                };
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
            };
        };
        put?: never;
        /**
         * Crear una categoria
         * @description Si no se indica slug, se genera del nombre y se le agrega un sufijo si ya existe. Si se indica a mano y esta tomado, se rechaza con CONFLICTO_DE_DATOS. La categoria nueva queda activa y al final del menu.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoriaEntrada"];
                };
            };
            responses: {
                /** @description Categoria creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoriaAdmin"];
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categorias/orden": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reordenar el menu
         * @description Recibe los ids de TODAS las categorias en el orden deseado. Se rechaza una lista con faltantes, repetidos o ids desconocidos: un orden parcial dejaria dos categorias en la misma posicion.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @example [
                         *       6,
                         *       4,
                         *       5
                         *     ]
                         */
                        ids: number[];
                    };
                };
            };
            responses: {
                /** @description Categorias en el orden nuevo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            datos?: components["schemas"]["CategoriaAdmin"][];
                        };
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categorias/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener una categoria */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categoria */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoriaAdmin"];
                    };
                };
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Editar una categoria
         * @description Solo se modifican los campos que vienen. Cambiar el nombre NO cambia el slug: para cambiar la URL hay que editar el slug a proposito. Si la categoria esta activa, el panel tiene que avisar que los links anteriores dejan de funcionar.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoriaCambios"];
                };
            };
            responses: {
                /** @description Categoria actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoriaAdmin"];
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
            };
        };
        trace?: never;
    };
    "/admin/categorias/{id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Activar o desactivar una categoria
         * @description Desactivar una categoria oculta de la tienda TODOS sus productos, aunque cada uno siga activo. La respuesta incluye cantidadProductos, y el panel tiene que informarlo antes de confirmar.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id del recurso. */
                    id: components["parameters"]["IdRuta"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        activa: boolean;
                    };
                };
            };
            responses: {
                /** @description Categoria con su estado nuevo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoriaAdmin"];
                    };
                };
                400: components["responses"]["DatosInvalidos"];
                401: components["responses"]["NoAutorizado"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado del servicio
         * @description Informa version, entorno y estado de la conexion a la base. Responde 200 aunque la base este caida; el estado va en el cuerpo.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Estado del servicio */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Salud"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Salud: {
            /** @example ok */
            estado: string;
            /** @example 1.0.0 */
            version: string;
            /** @example development */
            entorno: string;
            /** @enum {string} */
            baseDatos: "conectada" | "desconectada";
        };
        /** @description Contrato unico de error. El frontend mapea el codigo a un texto legible segun el contexto donde aparece. */
        Error: {
            /**
             * @description Codigo de dominio estable.
             * @example NO_ENCONTRADO
             */
            error: string;
            /** @description Solo en DATOS_INVALIDOS. Un mensaje por campo con error. */
            details?: {
                [key: string]: string;
            };
        };
        Meta: {
            /** @example 1 */
            pagina: number;
            /** @example 20 */
            limite: number;
            /**
             * @description Total de elementos que cumplen el filtro, no de la pagina.
             * @example 47
             */
            total: number;
        };
        Categoria: {
            /** @example 3 */
            id: number;
            /** @example Jabones */
            nombre: string;
            /** @example jabones */
            slug: string;
            /** @example Jabones artesanales en frio */
            descripcion?: string | null;
            /** Format: uri */
            imagenUrl?: string | null;
        };
        Imagen: {
            /** Format: uri */
            url: string;
            alt?: string | null;
        };
        Variante: {
            /** @example 12 */
            id: number;
            /**
             * @description Tamano o presentacion.
             * @example 100 g
             */
            nombre: string;
            /** @example JAB-CAL-100 */
            sku?: string | null;
            /**
             * @description Cadena decimal. No operar en el frontend.
             * @example 12500.00
             */
            precio: string;
            /**
             * @description Precio tachado. El badge de oferta se muestra SOLO si existe y es mayor que precio.
             * @example 15000.00
             */
            precioAnterior?: string | null;
            /** @description Si la variante tiene unidades disponibles. */
            hayStock: boolean;
        };
        /** @description Imagen principal: la primera segun su orden. Null si el producto todavia no tiene fotos. */
        ProductoListado: {
            /** @example 7 */
            id: number;
            /** @example Jabon Vegetal - Calendula y Karite */
            nombre: string;
            /** @example jabon-calendula-karite */
            slug: string;
            descripcionCorta?: string | null;
            categoria: components["schemas"]["Categoria"];
            /** @description Imagen principal, la de orden 0. Null si el producto todavia no tiene fotos. */
            imagen?: components["schemas"]["Imagen"] | null;
            /**
             * @description Precio minimo entre las variantes activas.
             * @example 12500.00
             */
            precioDesde: string;
            /** @description Precio anterior de la variante mas barata, si esta en oferta. */
            precioAnteriorDesde?: string | null;
            /** @description True si al menos una variante activa tiene stock. */
            hayStock: boolean;
            destacado: boolean;
        };
        /** @description Ficha completa del producto. */
        ProductoDetalle: {
            /** @example 7 */
            id: number;
            /** @example Jabon Vegetal - Calendula y Karite */
            nombre: string;
            /** @example jabon-calendula-karite */
            slug: string;
            descripcionCorta?: string | null;
            descripcion?: string | null;
            /** @description Listado tal como va en la etiqueta. */
            ingredientes?: string | null;
            modoUso?: string | null;
            destacado: boolean;
            categoria: components["schemas"]["Categoria"];
            /** @description Todas las imagenes, ordenadas. La primera es la principal. */
            imagenes: components["schemas"]["Imagen"][];
            /** @description Variantes activas. Siempre hay al menos una. */
            variantes: components["schemas"]["Variante"][];
        };
        LoginEntrada: {
            /**
             * Format: email
             * @example duena@veluanature.com.ar
             */
            email: string;
            password: string;
        };
        Usuario: {
            /** @example 1 */
            id: number;
            /** @example Dueña de la marca */
            nombre: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            rol: "admin" | "operador";
            /**
             * @example [
             *       "CATALOGO_VER",
             *       "CATALOGO_EDITAR"
             *     ]
             */
            permisos: string[];
        };
        /** @description Categoria vista desde el panel. Incluye las inactivas. */
        CategoriaAdmin: {
            /** @example 5 */
            id: number;
            /** @example L’Art du Savon */
            nombre: string;
            /** @example art-du-savon */
            slug: string;
            descripcion?: string | null;
            /** Format: uri */
            imagenUrl?: string | null;
            /** @example 2 */
            orden: number;
            activa: boolean;
            /**
             * @description Productos activos de la categoria. Desactivarla los oculta a todos de la tienda.
             * @example 6
             */
            cantidadProductos: number;
        };
        CategoriaEntrada: {
            /** @example Shampoo Sólido */
            nombre: string;
            /** @description Opcional. Si no viene se genera del nombre. Si viene y esta tomado, se rechaza. */
            slug?: string | null;
            descripcion?: string | null;
            /** Format: uri */
            imagenUrl?: string | null;
        };
        /** @description Solo se modifican los campos que vienen. Cambiar el nombre no cambia el slug. */
        CategoriaCambios: {
            nombre?: string;
            slug?: string | null;
            descripcion?: string | null;
            /** Format: uri */
            imagenUrl?: string | null;
        };
        /** @description Variante vista desde el panel. A diferencia de la tienda, expone el stock real. */
        VarianteAdmin: {
            /** @example 10 */
            id: number;
            /** @example 100 g */
            nombre: string;
            /** @example VEL-ECLAT-NOIR */
            sku?: string | null;
            /**
             * @description Cadena decimal.
             * @example 8500.00
             */
            precio: string;
            /** @example 9900.00 */
            precioAnterior?: string | null;
            /** @example 12 */
            stock: number;
            /** @example 100 */
            pesoGramos?: number | null;
            activa: boolean;
        };
        ImagenAdmin: {
            /** @example 3 */
            id: number;
            /** Format: uri */
            url: string;
            alt?: string | null;
            /** @example 0 */
            orden: number;
        };
        /** @description Fila de la grilla del panel, con los totales resumidos. */
        ProductoAdminFila: {
            /** @example 7 */
            id: number;
            /** @example Éclat Noir */
            nombre: string;
            /** @example eclat-noir */
            slug: string;
            descripcionCorta?: string | null;
            activo: boolean;
            destacado: boolean;
            categoria?: components["schemas"]["Categoria"];
            /**
             * @description Variantes activas.
             * @example 2
             */
            cantidadVariantes: number;
            /** @example 8500.00 */
            precioDesde?: string | null;
            /**
             * @description Suma del stock de las variantes activas.
             * @example 20
             */
            stockTotal: number;
            /** @example 3 */
            cantidadImagenes: number;
        };
        /** @description Ficha completa del producto en el panel, con todas sus variantes e imagenes. */
        ProductoAdmin: {
            /** @example 7 */
            id: number;
            nombre: string;
            slug: string;
            descripcionCorta?: string | null;
            descripcion?: string | null;
            ingredientes?: string | null;
            modoUso?: string | null;
            activo: boolean;
            destacado: boolean;
            categoria?: components["schemas"]["Categoria"];
            /** @description Todas, activas e inactivas. */
            variantes: components["schemas"]["VarianteAdmin"][];
            imagenes: components["schemas"]["ImagenAdmin"][];
        };
        VarianteEntrada: {
            /** @example 100 g */
            nombre: string;
            sku?: string | null;
            /**
             * @description Se acepta con punto o coma. Se guarda con dos decimales.
             * @example 8500
             */
            precio: string | number;
            /**
             * @description Tiene que ser MAYOR que precio. Si fuera igual o menor, la oferta seria de cero por ciento.
             * @example 9900
             */
            precioAnterior?: (string | number) | null;
            /** @default 0 */
            stock: number;
            pesoGramos?: number | null;
        };
        /** @description Solo se modifican los campos que vienen. */
        VarianteCambios: {
            nombre?: string;
            sku?: string | null;
            precio?: string | number;
            /** @description En null quita la oferta. */
            precioAnterior?: (string | number) | null;
            stock?: number;
            pesoGramos?: number | null;
        };
        ProductoEntrada: {
            categoriaId: number;
            nombre: string;
            /** @description Opcional. Si no viene se genera del nombre. Si viene y esta tomado, se rechaza. */
            slug?: string | null;
            descripcionCorta?: string | null;
            descripcion?: string | null;
            ingredientes?: string | null;
            modoUso?: string | null;
            /** @default false */
            destacado: boolean;
            /** @description Al menos una. El esquema no admite productos sin variantes. */
            variantes: components["schemas"]["VarianteEntrada"][];
        };
        /** @description Solo se modifican los campos que vienen. No toca las variantes. */
        ProductoCambios: {
            categoriaId?: number;
            nombre?: string;
            slug?: string | null;
            descripcionCorta?: string | null;
            descripcion?: string | null;
            ingredientes?: string | null;
            modoUso?: string | null;
            destacado?: boolean;
        };
    };
    responses: {
        /** @description Datos invalidos. details trae un mensaje por campo. */
        DatosInvalidos: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "DATOS_INVALIDOS",
                 *       "details": {
                 *         "nombre": "El nombre es obligatorio"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sin sesion, token invalido o expirado. */
        NoAutorizado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "NO_AUTORIZADO"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description La sesion es valida pero el rol no tiene el permiso requerido. */
        SinPermiso: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "SIN_PERMISO"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No existe un recurso con ese id. */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "NO_ENCONTRADO"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description El slug ya esta en uso. */
        Conflicto: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "CONFLICTO_DE_DATOS"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Numero de pagina, empezando en 1. */
        Pagina: number;
        /** @description Id del recurso. */
        IdRuta: number;
        /** @description Id de la variante dentro del producto. */
        VarianteIdRuta: number;
        /** @description Id de la imagen dentro del producto. */
        ImagenIdRuta: number;
        /** @description Cantidad de elementos por pagina. */
        Limite: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
